name: vehicle_streaming_analytics
version: 1.0.0
config-version: 2

profile: vehicle_streaming_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  vehicle_streaming_analytics:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: analytics
      +materialized: table
