vehicle_streaming_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: flinkuser
      password: flinkpw
      dbname: vehicle_db
      schema: public
      threads: 4
